chore: build process gains --with-profile and --with-features arguments

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,3 +1,29 @@
 #!/usr/bin/env sh
+
+# Initialize variables
+FEATURES_LIST=""
+PROFILE=""
+
+# Parse and validate configure arguments
+for arg in "$@"; do
+  case $arg in
+    --with-features=*)
+      value="${arg#*=}"
+      if [ -n "$FEATURES_LIST" ]; then
+        FEATURES_LIST="${FEATURES_LIST},${value}"
+      else
+        FEATURES_LIST="${value}"
+      fi
+      ;;
+    --with-profile=*)
+      PROFILE="${arg#*=}"
+      ;;
+    *)
+      echo "configure: error: unknown argument: $arg" >&2
+      exit 1
+      ;;
+  esac
+done
+
 : "${R_HOME=`R RHOME`}"
-"${R_HOME}/bin/Rscript" tools/config.R 
+"${R_HOME}/bin/Rscript" tools/config.R "${PROFILE}" "${FEATURES_LIST}"
